### ISSUE TITLE
[PE-D][Tester A] Book appt recurring 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T17-4/tp#212]
![Screenshot 2022-10-28 at 4.40.02 PM.png](https://raw.githubusercontent.com/Evande1/ped/main/files/a51c7bc9-f2d2-4ac8-aa49-cf8cec9a02a4.png)

Recurring appointment not changing the date after marked?

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Evande1/ped#4

**Comment by JovonLim** [comment]
I think this issue is referring that the original appointment date is unchanged, but has disregarded the fact that another appointment has been booked. Our solution was to not edit the original appointment date as in a real world setting, records of all appointments should be kept. Perhaps the tester did not read through the user guide thoroughly. Proposed to ignore this, but also keep in mind to test the recurring mechanism
